name: Compile kernel a15-6-6

permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
  
on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        # description: "Select KernelSU | Note: Select MKSU for the standard version"
        description: "Select KernelSU"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "Select the ksu branch"
        required: true
        type: choice
        options:
          - Stable
          - Dev
          - Other
        default: Stable
      version:
        description: 'Custom version name (e.g. 6.6.77-android15-8<custom version name>/leave blank to use the default version number)'
        required: false
        type: string
      build_time:
        description: 'Set kernel build time (format see repository description)'
        required: false
        type: string
      use_zram:
        description: 'Do you want to enable adding more ZRAM algorithms?'
        required: true
        type: boolean
        default: true
      use_bbg:
        description: 'Do you want to enable the BBG write-blocking patch? (Disable it if it reports an error)'
        required: true
        type: boolean
        default: true
      use_kpm:
        description: 'Do you want the KPM function enabled?'
        required: true
        type: boolean
        default: true
      supp_op:
        description: 'Do you want to enable support for OnePlus 8E processor models? (No need to check if it is not the model)'
        required: false
        type: boolean
        default: false
      get_manager:
        description: 'Get the latest KSU Manager and SUSFS modules?'
        required: true
        type: boolean
        default: true
      onlyAk3:
        description: 'Upload only AK3 compressed package? (No boot, faster download)'
        required: false
        type: boolean
        default: false

jobs:

  build-kernel-a15-6-6:
    uses: ./.github/workflows/kernel-a15-6.6.yml
    secrets: inherit
    with:
      make_release: false
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ inputs.version }}
      use_zram: ${{ inputs.use_zram }}
      use_bbg: ${{ inputs.use_bbg }}
      use_kpm: ${{ inputs.use_kpm }}
      supp_op: ${{ inputs.supp_op }}
      onlyAk3: ${{ inputs.onlyAk3 }}
      build_time: ${{ inputs.build_time }}
  get-ksu-manager:
    if: ${{ inputs.get_manager }}
    uses: ./.github/workflows/get-manager.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
  releasesuki:
    if: ${{ inputs.kernelsu_variant == 'SukiSU' }}
    uses: ./.github/workflows/releasesuki.yml
    secrets: inherit
    needs:
      - build-kernel-a15-6-6
      - get-ksu-manager
  releaseksu:
    if: ${{ inputs.kernelsu_variant == 'Official' }}
    uses: ./.github/workflows/releaseksu.yml
    secrets: inherit
    needs:
      - build-kernel-a15-6-6
      - get-ksu-manager
  releasemksu:
    if: ${{ inputs.kernelsu_variant == 'MKSU' }}
    uses: ./.github/workflows/releasemksu.yml
    secrets: inherit
    needs:
      - build-kernel-a15-6-6
      - get-ksu-manager
  releasenext:
    if: ${{ inputs.kernelsu_variant == 'Next' }}
    uses: ./.github/workflows/releasenext.yml
    secrets: inherit
    needs:
      - build-kernel-a15-6-6
      - get-ksu-manager
